# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.display_api import DisplayApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDisplayApi(unittest.TestCase):
    """DisplayApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.display_api.DisplayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_display_default_layout(self):
        """Test case for display_default_layout

        Set Default Layout  # noqa: E501
        """
        pass

    def test_display_delete(self):
        """Test case for display_delete

        Display Delete  # noqa: E501
        """
        pass

    def test_display_edit(self):
        """Test case for display_edit

        Display Edit  # noqa: E501
        """
        pass

    def test_display_request_screenshot(self):
        """Test case for display_request_screenshot

        Request Screen Shot  # noqa: E501
        """
        pass

    def test_display_search(self):
        """Test case for display_search

        Display Search  # noqa: E501
        """
        pass

    def test_display_toggle_authorise(self):
        """Test case for display_toggle_authorise

        Toggle authorised  # noqa: E501
        """
        pass

    def test_display_wake_on_lan(self):
        """Test case for display_wake_on_lan

        Issue WOL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
