# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.display_group import DisplayGroup  # noqa: E501
from swagger_client.rest import ApiException


class TestDisplayGroup(unittest.TestCase):
    """DisplayGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDisplayGroup(self):
        """Test DisplayGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.display_group.DisplayGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
