# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.playlist_api import PlaylistApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaylistApi(unittest.TestCase):
    """PlaylistApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.playlist_api.PlaylistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_playlist_library_assign(self):
        """Test case for playlist_library_assign

        Assign Library Items  # noqa: E501
        """
        pass

    def test_playlist_order(self):
        """Test case for playlist_order

        Order Widgets  # noqa: E501
        """
        pass

    def test_playlist_search(self):
        """Test case for playlist_search

        Playlist Widget Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
