# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.command_api import CommandApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommandApi(unittest.TestCase):
    """CommandApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.command_api.CommandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_command_add(self):
        """Test case for command_add

        Command Add  # noqa: E501
        """
        pass

    def test_command_delete(self):
        """Test case for command_delete

        Delete Command  # noqa: E501
        """
        pass

    def test_command_edit(self):
        """Test case for command_edit

        Edit Command  # noqa: E501
        """
        pass

    def test_command_search(self):
        """Test case for command_search

        Command Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
