# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.audit_log import AuditLog  # noqa: E501
from swagger_client.rest import ApiException


class TestAuditLog(unittest.TestCase):
    """AuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLog(self):
        """Test AuditLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.audit_log.AuditLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
