# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.resolution_api import ResolutionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestResolutionApi(unittest.TestCase):
    """ResolutionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.resolution_api.ResolutionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resolution_add(self):
        """Test case for resolution_add

        Add Resolution  # noqa: E501
        """
        pass

    def test_resolution_delete(self):
        """Test case for resolution_delete

        Delete Resolution  # noqa: E501
        """
        pass

    def test_resolution_edit(self):
        """Test case for resolution_edit

        Edit Resolution  # noqa: E501
        """
        pass

    def test_resolution_search(self):
        """Test case for resolution_search

        Resolution Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
