# coding: utf-8

# flake8: noqa
"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.application import Application
from swagger_client.models.audit_log import AuditLog
from swagger_client.models.campaign import Campaign
from swagger_client.models.command import Command
from swagger_client.models.data_set import DataSet
from swagger_client.models.data_set_column import DataSetColumn
from swagger_client.models.data_set_column_type import DataSetColumnType
from swagger_client.models.data_type import DataType
from swagger_client.models.day_part import DayPart
from swagger_client.models.display import Display
from swagger_client.models.display_group import DisplayGroup
from swagger_client.models.display_profile import DisplayProfile
from swagger_client.models.help import Help
from swagger_client.models.layout import Layout
from swagger_client.models.layout_assignment_array import LayoutAssignmentArray
from swagger_client.models.log_entry import LogEntry
from swagger_client.models.media import Media
from swagger_client.models.module import Module
from swagger_client.models.module_widget import ModuleWidget
from swagger_client.models.notification import Notification
from swagger_client.models.page import Page
from swagger_client.models.permission import Permission
from swagger_client.models.playlist import Playlist
from swagger_client.models.playlist_widget_list import PlaylistWidgetList
from swagger_client.models.region import Region
from swagger_client.models.region_option import RegionOption
from swagger_client.models.resolution import Resolution
from swagger_client.models.schedule import Schedule
from swagger_client.models.schedule_calendar_data import ScheduleCalendarData
from swagger_client.models.statistics_data import StatisticsData
from swagger_client.models.tag import Tag
from swagger_client.models.transition import Transition
from swagger_client.models.user import User
from swagger_client.models.user_group import UserGroup
from swagger_client.models.user_notification import UserNotification
from swagger_client.models.user_option import UserOption
from swagger_client.models.widget import Widget
from swagger_client.models.widget_audio import WidgetAudio
from swagger_client.models.widget_option import WidgetOption
