# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RegionOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_id': 'int',
        'option': 'str',
        'value': 'str'
    }

    attribute_map = {
        'region_id': 'regionId',
        'option': 'option',
        'value': 'value'
    }

    def __init__(self, region_id=None, option=None, value=None):  # noqa: E501
        """RegionOption - a model defined in Swagger"""  # noqa: E501

        self._region_id = None
        self._option = None
        self._value = None
        self.discriminator = None

        if region_id is not None:
            self.region_id = region_id
        if option is not None:
            self.option = option
        if value is not None:
            self.value = value

    @property
    def region_id(self):
        """Gets the region_id of this RegionOption.  # noqa: E501

        The regionId that this Option applies to  # noqa: E501

        :return: The region_id of this RegionOption.  # noqa: E501
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this RegionOption.

        The regionId that this Option applies to  # noqa: E501

        :param region_id: The region_id of this RegionOption.  # noqa: E501
        :type: int
        """

        self._region_id = region_id

    @property
    def option(self):
        """Gets the option of this RegionOption.  # noqa: E501

        The option name  # noqa: E501

        :return: The option of this RegionOption.  # noqa: E501
        :rtype: str
        """
        return self._option

    @option.setter
    def option(self, option):
        """Sets the option of this RegionOption.

        The option name  # noqa: E501

        :param option: The option of this RegionOption.  # noqa: E501
        :type: str
        """

        self._option = option

    @property
    def value(self):
        """Gets the value of this RegionOption.  # noqa: E501

        The option value  # noqa: E501

        :return: The value of this RegionOption.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RegionOption.

        The option value  # noqa: E501

        :param value: The value of this RegionOption.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegionOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
