# coding: utf-8

"""
    Xibo API

    Xibo CMS API  # noqa: E501

    OpenAPI spec version: 1.8.0
    Contact: info@xibo.org.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class StatisticsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def stats_search(self, **kwargs):  # noqa: E501
        """stats_search  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.stats_search(async=True)
        >>> result = thread.get()

        :param async bool
        :param str type: The type of stat to return. Layout|Media|Widget or All
        :param str from_dt: The start date for the filter. Default = 24 hours ago
        :param str to_dt: The end date for the filter. Default = now.
        :param int display_id: An optional display Id to filter
        :param list[int] layout_id: An optional array of layout Id to filter
        :param list[int] media_id: An optional array of media Id to filter
        :return: list[StatisticsData]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.stats_search_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.stats_search_with_http_info(**kwargs)  # noqa: E501
            return data

    def stats_search_with_http_info(self, **kwargs):  # noqa: E501
        """stats_search  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.stats_search_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str type: The type of stat to return. Layout|Media|Widget or All
        :param str from_dt: The start date for the filter. Default = 24 hours ago
        :param str to_dt: The end date for the filter. Default = now.
        :param int display_id: An optional display Id to filter
        :param list[int] layout_id: An optional array of layout Id to filter
        :param list[int] media_id: An optional array of media Id to filter
        :return: list[StatisticsData]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['type', 'from_dt', 'to_dt', 'display_id', 'layout_id', 'media_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method stats_search" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'type' in params:
            form_params.append(('type', params['type']))  # noqa: E501
        if 'from_dt' in params:
            form_params.append(('fromDt', params['from_dt']))  # noqa: E501
        if 'to_dt' in params:
            form_params.append(('toDt', params['to_dt']))  # noqa: E501
        if 'display_id' in params:
            form_params.append(('displayId', params['display_id']))  # noqa: E501
        if 'layout_id' in params:
            form_params.append(('layoutId', params['layout_id']))  # noqa: E501
            collection_formats['layoutId'] = 'csv'  # noqa: E501
        if 'media_id' in params:
            form_params.append(('mediaId', params['media_id']))  # noqa: E501
            collection_formats['mediaId'] = 'csv'  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['auth']  # noqa: E501

        return self.api_client.call_api(
            '/stats', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[StatisticsData]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
